[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "expense-tracker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["typer", "rich"]

[project.scripts]
expense-tracker = "expense_tracker.expense_tracker:app"